name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-hardhat-chainlink-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Setup environment
        working-directory: packages/hardhat-chainlink
        run: yarn && yarn typechain && yarn build && yarn test:prepare
      
      - name: Test chainlink:dataFeed module
        working-directory: packages/hardhat-chainlink
        run: yarn test:dataFeed
      
      - name: Test chainlink:dataFeedProxy module
        working-directory: packages/hardhat-chainlink
        run: yarn test:dataFeedProxy
      
      - name: Test chainlink:feedRegistry module
        working-directory: packages/hardhat-chainlink
        run: yarn test:feedRegistry
      
      - name: Test chainlink:vrf module
        working-directory: packages/hardhat-chainlink
        run: yarn test:vrfCoordinator
      
      - name: Test chainlink:automationRegistrar module
        working-directory: packages/hardhat-chainlink
        run: yarn test:automationRegistrar
      
      - name: Test chainlink:automationRegistry module
        working-directory: packages/hardhat-chainlink
        run: yarn test:automationRegistry
